use crate::{config::GalleryConfig, gallery::ImageEntry, handlers::encode_path};

const TEMPLATE: &str = include_str!("../templates/gallery.html");

/// Render the gallery HTML, injecting the image list and secrets so that
/// all thumbnail/full-size URLs generated by the JS carry the correct
/// `?secret=` query parameter automatically.
pub fn render(gallery: &GalleryConfig, images: &[ImageEntry], secret: &str) -> String {
    let images_json = {
        let mut buf = String::from("[");
        for (i, img) in images.iter().enumerate() {
            if i > 0 {
                buf.push(',');
            }
            // Append secret as query param when present.
            let qs = if !secret.is_empty() {
                format!("?secret={}", url_encode(secret))
            } else {
                String::new()
            };
            let thumb_url = format!("/{}/thumb/{}{}", gallery.url, encode_path(&img.path), qs);
            let full_url  = format!("/{}/full/{}{}", gallery.url, encode_path(&img.path), qs);
            let name = img.filename.replace('\\', "\\\\").replace('"', "\\\"");
            buf.push_str(&format!(
                r#"{{"thumb":"{thumb_url}","full":"{full_url}","name":"{name}"}}"#
            ));
        }
        buf.push(']');
        buf
    };

    let count = format!(
        "{} photo{}",
        images.len(),
        if images.len() == 1 { "" } else { "s" }
    );

    TEMPLATE
        .replace("__TITLE__", &html_escape(&gallery.name))
        .replace("__IMAGES_JSON__", &images_json)
        .replace("__COUNT__", &count)
}

fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

/// Percent-encode a secret value so it is safe in a URL query string.
fn url_encode(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for b in s.bytes() {
        match b {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9'
            | b'-' | b'_' | b'.' | b'~' => out.push(b as char),
            _ => out.push_str(&format!("%{b:02X}")),
        }
    }
    out
}
